import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex items-center justify-between p-4">
        <h1>Frontend Mentor</h1>

        <button className="rounded-xl bg-gray-700 px-4 py-1 text-white hover:bg-gray-600">
          Click
        </button>
      </nav>

      <main>
        <h1 className="bg-sky-700 px-4 py-2 text-white hover:bg-sky-800 sm:px-8 sm:py-3">
          Hello World!
        </h1>
      </main>
    </>
  );
}
